services:
  demo1:
    build: .
    ports:
      - "8081:8080"
  demo2:
    build: C:\Users\marzenusia\IdeaProjects\demo2\
    ports:
      - "8082:8081"
  db:
    image: mysql
    environment:
      - "MYSQL_ROOT_PASSWORD=abc3"
      - "MYSQL_DATABASE=db_example"
    ports:
      - "3307:3306"